apisix:
  enable_admin: false
  config_center: yaml
  extra_lua_path: "/opt/?.lua"
plugins:
  - proxy-rewrite         # priority: 1008
  - public-api            # priority:  501
  - bff                   # priority:  100
